Closes #15 Ajustes en la Base de Datos
proyectodaw202223/StoreAPI pull request #18
Opened 2022-12-01 21:12 UTC by romomartin

2022-12-02 14:46 UTC, afidalgobirt requested changes

2022-12-02 14:46 UTC, afidalgobirt commented on database/migrations/2022_10_29_143858_create_product_items_table.php
> +                'ONE_SIZE'
Lo de ONE_SIZE es el texto que se va a guardar en la base de datos y lo que se devuelve en JSON al hacer una petición, yo pondria `Única` para poder sacarlo en el cliente tal cual está en el JSON y en el enum pondria `case ONE_SIZE = "Única"`

2022-12-13 21:34 UTC, romomartin commented on database/migrations/2022_10_29_143858_create_product_items_table.php
> +                'ONE_SIZE'
Modificado.

2022-12-17 11:10 UTC, afidalgobirt requested changes
Faltaba una cosilla de los cambios anteriores y he añadido un cambio mas.

2022-12-17 11:10 UTC, afidalgobirt commented on app/Enums/UserRole.php
> +    case Administrador = "Administrador";
Yo pondría el case en mayúsculas y en ingles por seguir la convención del resto de las enumeraciones, al final es como una variable constante.
```suggestion
    case ADMIN = "Administrador";
```

2022-12-17 11:10 UTC, afidalgobirt commented on database/migrations/2022_10_29_143858_create_product_items_table.php
> +                'ONE_SIZE'
Lo has cambiado en el enum pero hay que cambiarlo aquí también, el texto del enum tiene que ser igual que lo que se guarde en la base de datos.
```suggestion
                'Única'
```

2022-12-17 11:20 UTC, afidalgobirt approved these changes

2022-12-17 11:21 UTC, merged